### ISSUE TITLE
multirecording = se.MultiRecordingTimeExtractor(recordings) - IndexError: index 107136280 is out of bounds for axis 0 with size 107136280

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#37]
Hi @luiztauffer  @alejoe91 . I am trying to concatenate 2 files and am getting this error message. Might this also be due to the time-offset differences betwen intan and CED?
![image](https://user-images.githubusercontent.com/43117750/118783895-cc28eb80-b88f-11eb-9432-c3020bd5494d.png)

**Comment by alejoe91** [comment]
@rf13734 I'll check this out! Probably this happens when concatenating 2 recordings with timestamps (like CED ones).

In the meanwhile, this should fix the resample issue: https://github.com/SpikeInterface/spiketoolkit/pull/485

**Comment by alejoe91** [comment]
@rf13734 this should be fixed on spikeextractors master: https://github.com/SpikeInterface/spikeextractors/pull/641/commits/a941fb1642faccf9bc4398d03b1b9bf9a5b8fde4

Can you test installing both spikeextractor and spiketoolkit from the official master? both this and the resampling problem shoudl be fixed

**Comment by rf13734** [comment]
@alejoe91  I tried this and now have a new error for self.set_channel_gains  during the recording = se.CEDRecordingExtractor(ced_file, smrx_channel_ids=rhd_channels)

![image](https://user-images.githubusercontent.com/43117750/119110546-8f412e00-ba22-11eb-8487-b7931ff92caa.png)


![image](https://user-images.githubusercontent.com/43117750/119111039-f9f26980-ba22-11eb-8199-858dfba71718.png)

**Comment by alejoe91** [comment]
@rf13734 spikeextractors is not installed from master. You have to to the clone + uninstall + python setup.py develop trick with this repo: 
https://github.com/SpikeInterface/spikeextractors

**Comment by rf13734** [comment]
@alejoe91 Ah yes, sorry!

**Comment by rf13734** [comment]
Thanks, now installed the new spiketoolkit and spikeextractors (I think) 
![image](https://user-images.githubusercontent.com/43117750/119115053-0678c100-ba27-11eb-9dc0-60530508fd9a.png)


But still getting a 30kHz sampling rate

![image](https://user-images.githubusercontent.com/43117750/119114906-dfba8a80-ba26-11eb-9be5-a37aeb4e45ba.png)

**Comment by alejoe91** [comment]
Yes that's not in master yet. or is it @luiztauffer ??

**Comment by rf13734** [comment]
@alejoe91 ah okay, I'll carry on through the pipeline, but so far so good!! Thanks!

**Comment by luiztauffer** [comment]
it is ready to come [here](https://github.com/SpikeInterface/spikeextractors/pull/643)

**Comment by rf13734** [comment]
@luiztauffer  However, when I swap out the file you used for the same file in my computer, I no longer get the corrected sampling frequency.

![image](https://user-images.githubusercontent.com/43117750/119492073-f3cff600-bd5e-11eb-9dc4-99a684c46b21.png)


![image](https://user-images.githubusercontent.com/43117750/119492151-077b5c80-bd5f-11eb-9a5e-3656e577eaa5.png)


![image](https://user-images.githubusercontent.com/43117750/119492462-6640d600-bd5f-11eb-912e-2985e013edb2.png)


![image](https://user-images.githubusercontent.com/43117750/119492426-5d500480-bd5f-11eb-926b-48faf7db4a28.png)

**Comment by luiztauffer** [comment]
are you sure you're checked out in the PR version?

**Comment by luiztauffer** [comment]
sorry for all these versioning headaches... they will cease once all changes get merged in their respective repos and we make the releases

**Comment by rf13734** [comment]
> are you sure you're checked out in the PR version?

@luiztauffer  Ah is this PR version the new version of fix_ced_2?

![image](https://user-images.githubusercontent.com/43117750/119495811-1b28c200-bd63-11eb-9b30-b8998c47d3a3.png)


I'll install this and try it out

**Comment by rf13734** [comment]
Works now! Thanks again!

![image](https://user-images.githubusercontent.com/43117750/119496639-faad3780-bd63-11eb-939f-0b9c5cc79041.png)
